const member_list = {
  members: {
    ptarsoly: {
      id: "ptarsoly",
      img_src: "./images/member_images/ptarsoly.png",
      name: "Peter W. Tarsoly",
      major: "Computer Engineering",
      number: 1,
      class: "2021",
      origin: "Huntington, NY",
      catchphrase: "",
    },
    gjacobellis: {
      id: "gjacobellis",
      img_src: "./images/member_images/gjacobellis.png",
      name: "Garrett A. Jacobellis",
      major: "Mechanical Engineering",
      number: 2,
      class: "2020",
      origin: "Huntington, NY",
      catchphrase: "",
    },
    skaynor: {
      id: "skaynor",
      img_src: "./images/member_images/skaynor.png",
      name: "Sam Kaynor",
      major: "Computer Engineering",
      class: "2022",
      catchphrase: "",
    },
    dmccook: {
      id: "dmccook",
      img_src: "./images/member_images/dmccook.png",
      name: "Dylan L. McCook",
      major: "Aerospace Engineering",
      number: 3,
      class: "2022",
      origin: "Liveoak, FL",
      catchphrase: "",
    },
    anoori: {
      id: "anoori",
      img_src: "./images/member_images/anoori.png",
      name: "Amanda Noori",
      major: "Aerospace Engineering",
      number: 4,
      class: "2019",
      origin: "Atlanta, GA",
      catchphrase: "",
    },
    dsouthwell: {
      id: "dsouthwell",
      img_src: "./images/member_images/dsouthwell.png",
      name: "Donovan Southwell",
      major: "Aerospace Engineering",
      number: 5,
      class: "2020",
      origin: "Indiatlantic, FL",
      catchphrase: "",
    },
    msyed: {
      id: "msyed",
      img_src: "./images/member_images/msyed.png",
      name: "Muntaser Syed",
      major: "Computer Engineering",
      number: 6,
      class: "2022",
      origin: "Abu Dhabi, UAE",
      catchphrase: "",
    },
    athierer: {
      id: "athierer",
      img_src: "./images/member_images/athierer.png",
      name: "Alexander B. Thierer",
      major: "Civil Engineering",
      number: 7,
      class: "2019",
      origin: "High Point, NC",
      catchphrase: "",
    },
    athornton: {
      id: "athornton",
      img_src: "./images/member_images/athornton.png",
      name: "Alana Thornton",
      major: "Mechanical Engineering",
      number: 8,
      class: "2019",
      origin: "Fort Washington, MD",
      catchphrase: "",
    },
    rwhitman: {
      id: "rwhitman",
      img_src: "./images/member_images/rwhitman.png",
      name: "Robert Whitman",
      major: "Computer Science",
      number: 9,
      class: "2021",
      origin: "Palm Bay, FL",
      catchphrase: "",
    },
    fswarr: {
      id: "fswarr",
      img_src: "./images/member_images/fswarr.png",
      name: "Fiona E. Swarr",
      major: "Mechanical Engineering",
      number: 10,
      class: "2022",
      origin: "Melbourne, FL",
      catchphrase: "",
    },
    sedwards: {
      id: "sedwards",
      img_src: "./images/member_images/sedwards.png",
      name: "Sarah Edwards",
      major: "Aerospace Engineering",
      number: 11,
      class: "202",
      origin: "Brentwood, TN",
      catchphrase: "",
    },
    crush: {
      id: "crush",
      img_src: "./images/member_images/crush.png",
      name: "Cassandra Rush",
      major: "Aerospace Engineering",
      number: 12,
      class: "2022",
      origin: "Pittsburgh, PA",
      catchphrase: "",
    },
    ahopkins: {
      id: "ahopkins",
      img_src: "./images/member_images/ahopkins.png",
      name: "Alexis Hopkins",
      major: "Biomedical Engineering",
      number: 13,
      class: "2021",
      origin: "",
      catchphrase: "",
    },
    mtapaszto: {
      id: "mtapaszto",
      img_src: "./images/member_images/mtapaszto.png",
      name: "Marcell Tapaszto",
      major: "Computer Engineering",
      number: 15,
      class: "2022",
      origin: "Kecskemet, Hungary",
      catchphrase: "",
    },
    measton: {
      id: "measton",
      img_src: "./images/member_images/measton.png",
      name: "Miranda Easton",
      major: "Aerospace Engineering",
      number: 16,
      class: "2023",
      origin: "Tallahassee, FL",
      catchphrase: "",
    },
    rgriffin: {
      id: "rgriffin",
      img_src: "./images/member_images/rgriffin.png",
      name: "Ryley P. Griffin",
      major: "Chemical Engineering",
      number: 17,
      class: "2022",
      origin: "Morgantown, WV",
      catchphrase: "",
    },
    lblackwell: {
      id: "lblackwell",
      img_src: "./images/member_images/lblackwell.png",
      name: "Landon C. Blackwell-Frank",
      major: "Mechanical Engineering",
      number: 18,
      class: "2024",
      origin: "The Woodlands, TX",
      catchphrase: "",
    },
    jhing: {
      id: "jhing",
      img_src: "./images/member_images/jhing.png",
      name: "Justing Hing",
      major: "Aerospace Engineering",
      number: 19,
      class: "2022",
      origin: "fort Lauterdale, FL",
      catchphrase: "",
    },
    mhoadley: {
      id: "mhoadley",
      img_src: "./images/member_images/mhoadley.png",
      name: "Michael Hoadley",
      number: 20,
      major: "Mechanical Engineering",
      class: "2022",
      origin: "Branford, CT",
      catchphrase: "Rockets and friends. Who needs more?",
    },
    ileon: {
      id: "ileon",
      img_src: "./images/member_images/ileon.png",
      name: "Ian León",
      major: "Aerospace Engineering",
      number: 21,
      class: "2022",
      origin: "San Jose, Costa Rica",
    },
    csisko: {
      id: "csisko",
      img_src: "./images/member_images/csisko.png",
      name: "Caroline Sisko",
      major: "Aerospace Engineering",
      number: 22,
      class: "2022",
      origin: "Inverness, FL",
      catchphrase: "",
    },
    rhutchison: {
      id: "rhutchison",
      img_src: "./images/member_images/rhutchinson.png",
      name: "Ryan Hutchison",
      major: "Aerospace Engineering",
      number: 23,
      class: "2022",
      origin: "Cocoa, FL",
      catchphrase: "",
    },
    dnieves: {
      id: "dnieves",
      img_src: "./images/member_images/dnieves.png",
      name: "David Nieves Acarón",
      major: "Computer Engineering",
      number: 24,
      class: "2022",
      origin: "San Juan, Puerto Rico",
      catchphrase: "",
    },
    grivasleal: {
      id: "grivasleal",
      img_src: "./images/member_images/grivasleal.png",
      name: "Gerardo Rivas Leal",
      major: "Computer Engineering",
      number: 25,
      class: "2022",
      origin: "Labelle, FL",
      catchphrase: "",
    },
    atisaranni: {
      id: "atisaranni",
      img_src: "./images/member_images/atisaranni.png",
      name: "Ashley L. Tisaranni",
      major: "Aerospace Engineering",
      number: 26,
      class: "2023",
      origin: "Germantown, MD",
      catchphrase: "",
    },
    kdecker: {
      id: "kdecker",
      img_src: "./images/member_images/kdecker.png",
      name: "Cypress Decker",
      major: "Aerospace Engineering",
      number: 27,
      class: "2022",
      origin: "Jacksonville, FL",
      catchphrase: "",
    },
    kforero: {
      id: "kforero",
      img_src: "./images/member_images/kforero.png",
      name: "Kathleen Forero",
      major: "Chemical Engineering",
      number: 28,
      class: "2023",
      origin: "",
      catchphrase: "",
      include: false,
    },
    amichalczyk: {
      id: "amichalczyk",
      img_src: "./images/member_images/kforero.png",
      name: "Alaina M. Michalczyk",
      major: "Mechnical Engineering",
      number: 29,
      class: "2023",
      origin: "Chayna",
      catchphrase: "",
      include: false,
    },
    asullivan: {
      id: "asullivan",
      img_src: "./images/member_images/asullivan.png",
      name: "Adli R. Sullivan",
      major: "Chemical Engineering",
      number: 30,
      class: "2023",
      origin: "",
      catchphrase: "",
    },
    swaddell: {
      id: "swaddell",
      img_src: "./images/member_images/swaddell.png",
      name: "Shelton Waddell",
      major: "Aerospace Engineering",
      number: 31,
      class: "2023",
      origin: "Melbourne, FL",
      catchphrase: "",
    },
    rblomquist: {
      id: "rblomquist",
      img_src: "./images/member_images/rblomquist.png",
      name: "Regan Blomquist",
      major: "Biomedical Engineering",
      number: 32,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    gmarrero: {
      id: "gmarrero",
      img_src: "./images/member_images/gmarrero.png",
      name: "Jay Marrero",
      major: "Aerospace Engineering",
      number: 33,
      class: "2023",
      origin: "Flushing, NY",
      catchphrase: "",
    },
    kmobley: {
      id: "kmobley",
      img_src: "./images/member_images/kmobley.png",
      name: "Ken Mobley",
      major: "Aerospace Engineering",
      number: 34,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    tpaige: {
      id: "tpaige",
      img_src: "./images/member_images/tpaige.png",
      name: "Trent Paige",
      major: "Aerospace Engineering",
      number: 35,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    cswords: {
      id: "cswords",
      img_src: "./images/member_images/cswords.png",
      name: "Carlie Swords",
      major: "Aerospace Engineering",
      number: 36,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    dbarnes: {
      id: "dbarnes",
      img_src: "./images/member_images/dbarnes.png",
      name: "Dylan Barnes",
      major: "Aerospace Engineering",
      number: 37,
      class: "2022",
      origin: "",
      catchphrase: "",
    },
    rhalcyon: {
      id: "rhalcyon",
      img_src: "./images/member_images/rhalcyon.png",
      name: "Rosemary Halcyon-Schmitt",
      major: "Chemical Engineering",
      number: 38,
      class: "",
      origin: "",
      catchphrase: "",
    },

    jjohnson: {
      id: "jjohnson",
      img_src: "./images/member_images/jjohnson.png",
      name: "Jordan Johnson",
      major: "Civil Engineering",
      number: 39,
      class: "2025",
      origin: "",
      catchphrase: "",
    },

    ajunkin: {
      id: "ajunkin",
      img_src: "./images/member_images/ajunkin.png",
      name: "Andrew Junkin",
      major: "Biomedical Engineering",
      number: 40,
      class: "2023",
      origin: "",
      catchphrase: "",
    },
    mlanahan: {
      id: "mlanahan",
      img_src: "./images/member_images/mlanahan.png",
      name: "Madison Lanahan",
      major: "Computer Science ",
      number: 41,
      class: "2026",
      origin: "",
      catchphrase: "",
    },
    dmcdaniels: {
      id: "dmcdaniels",
      img_src: "./images/member_images/dmcdaniels.png",
      name: "Devlin McDaniels",
      major: "Aerospace Engineering",
      number: 42,
      class: "2022",
      origin: "",
      catchphrase: "",
    },
    vshirley: {
      id: "vshirley",
      img_src: "./images/member_images/vshirley.png",
      name: "Val Shirley",
      major: "Aerospace Engineering",
      number: 43,
      class: "2023",
      origin: "",
      catchphrase: "",
    },
    kweaver: {
      id: "kweaver",
      img_src: "./images/member_images/kweaver.png",
      name: "Keelin Weaver",
      major: "Aerospace Engineering",
      number: 44,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    czinninger: {
      id: "czinninger",
      img_src: "./images/member_images/czinninger.png",
      name: "Charlotte Zinninger",
      major: "Aerospace Engineering",
      number: 45,
      class: "2025",
      origin: "Syracyse, NY",
      catchphrase: "",
    },
    oloris: {
      id: "oloris",
      img_src: "./images/member_images/oloris.png",
      name: "Olivia Loris",
      major: "Software Engineering",
      number: 46,
      class: "2026",
      origin: "",
      catchphrase: "",
    },
    gspitaletto: {
      id: "gspitaletto",
      img_src: "./images/member_images/gspitaletto.png",
      name: "Genevieve Spitaletto",
      major: "Civil Engineering",
      number: 47,
      class: "",
      origin: "",
      catchphrase: "",
    },
    astringer: {
      id: "astringer",
      img_src: "./images/member_images/astringer.png",
      name: "Ashton Stringer",
      major: "Mechanical Engineering",
      number: 48,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    zhardin: {
      id: "zhardin",
      img_src: "./images/member_images/zhardin.png",
      name: "Zachary Hardin",
      major: "Mechanical Engineering",
      number: 49,
      class: "2026",
      origin: "Rock Island, Illinois",
      catchphrase: "",
    },
    amoore: {
      id: "amoore",
      img_src: "./images/member_images/amoore.png",
      name: "Archer Moore",
      major: "Chemical Engineering",
      number: 50,
      class: "2024",
      origin: "",
      catchphrase: "",
    },
    gmorales: {
      id: "gmorales",
      img_src: "./images/member_images/gmorales.png",
      name: "Gabriel Morales",
      major: "Software Engineering",
      number: 51,
      class: "2026",
      origin: "North Carolina",
      catchphrase: "",
    },
    elizabeth: {
      id: "elizabeth",
      img_src: "",
      name: "Elizabeth",
      major: "?",
      catchphrase: "",
    },
  afrench: {
      id: "afrench",
      img_src: "",
      name: "Alex French",
      major: "Mechanical Engineering",
      number: "57",
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    eclark: {
      id: "eclark",
      img_src: "",
      name: "Ember Clark",
      major: "Computer Engineering",
      number: "54",
      class: "2027",
      origin: "",
      catchphrase: "",
    },
    pczaja: {
      id: "pczaja",
      img_src: "",
      name: "Peter Czaja",
      major: "Biomedical Engineering",
      number: "55",
      class: "2027",
      origin: "",
      catchphrase: "",
    },
    sfijnvandraat: {
      id: "sfijnvandraat",
      img_src: "",
      name: "Sarah Fijnvandraat",
      major: "Biomedical Engineering",
      number: "56",
      class: "2027",
      origin: "",
      catchphrase: "",
    },
    cgaspar: {
      id: "cgaspar",
      img_src: "",
      name: "Calvin Gaspar",
      major: "Aerospace Engineering",
      number: "58",
      class: "2027",
      origin: "",
      catchphrase: "",
    },
    ljohnson: {
      id: "ljohnson",
      img_src: "",
      name: "Londyn Johnson",
      major: "",
      number: "59",
      class: "2027",
      origin: "",
      catchphrase: "",
    },
    jnichols: {
      id: "jnichols",
      img_src: "",
      name: "Jason Nichols",
      major: "Electrical Engineering",
      number: "62",
      class: "2027",
      origin: "",
      catchphrase: "",
    },
    jstevens: {
      id: "jstevens",
      img_src: "",
      name: "Jasper Stevens",
      major: "Mechanical Engineering",
      number: "64",
      class: "2027",
      origin: "",
      catchphrase: "",
    },
    ctomasky: {
      id: "ctomasky",
      img_src: "",
      name: "Carter Tomasky",
      major: "Mechanical Engineering",
      number: "66",
      class: "2028",
      origin: "",
      catchphrase: "",
    },
    ccapawana: {
      id: "ccapawana",
      img_src: "",
      name: "Cole Capawana",
      major: "Aerospace Engineering",
      number: "68",
      class: "2028",
      origin: "",
      catchphrase: "",
    },
    egreen: {
      id: "egreen",
      img_src: "",
      name: "Erik Green",
      major: "Aerospace Engineering",
      number: "69",
      class: "2027",
      origin: "",
      catchphrase: "",
    },
    aquarra: {
      id: "aquarra",
      img_src: "",
      name: "Arthur Quarra",
      major: "Computer Science",
      number: "71",
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    ahaughwout: {
      id: "ahaughwout",
      img_src: "",
      name: "Avery Haughwout",
      major: "",
      number: "72",
      class: "2028",
      origin: "",
      catchphrase: "",
    },
    tross: {
      id: "tross",
      img_src: "",
      name: "Taylor Ross",
      major: "Aerospace Engineering",
      number: "73",
      class: "2029",
      origin: "",
      catchphrase: "",
    },
  },
  regents: {
    previous: {
      "2018-2019": ["ptarsoly"], // Peter (colony regent)
      "2019-2020": ["crush"], // Cassandra
      "2020-2021": ["fswarr"], // Fiona
      "2021-2022": ["measton", "ileon"], // Ran, Ian
      "2022-2023": ["gmarrero"], // Jay
      "2024-2025": ["afrench"], //Alex
    },
    current: "ccapawana", // Cole
  },
  linkDataArray: [
    { group: "edges", data: { source: "dsouthwell", target: "mtapaszto" } },
    { group: "edges", data: { source: "mtapaszto", target: "mhoadley" } },
    { group: "edges", data: { source: "mtapaszto", target: "swaddell" } },
    { group: "edges", data: { source: "mtapaszto", target: "dbarnes" } },
    { group: "edges", data: { source: "mtapaszto", target: "astringer" } },
    { group: "edges", data: { source: "mhoadley", target: "dnieves" } },
    { group: "edges", data: { source: "mhoadley", target: "rblomquist" } },
    { group: "edges", data: { source: "mhoadley", target: "ajunkin" } },
    { group: "edges", data: { source: "dnieves", target: "czinninger" } },
    { group: "edges", data: { source: "dnieves", target: "zhardin" } },
    { group: "edges", data: { source: "dnieves", target: "kforero" } },
    { group: "edges", data: { source: "dnieves", target: "afrench" } },
    { group: "edges", data: { source: "dnieves", target: "dcruz" } },
    { group: "edges", data: { source: "czinninger", target: "gmorales" } },
    { group: "edges", data: { source: "czinninger", target: "eclark" } },
    { group: "edges", data: { source: "czinninger", target: "kmobley" } },
    { group: "edges", data: { source: "athierer", target: "sedwards" } },
    { group: "edges", data: { source: "sedwards", target: "jhing" } },
    { group: "edges", data: { source: "jhing", target: "grivasleal" } },
    { group: "edges", data: { source: "jhing", target: "gmarrero" } },
    { group: "edges", data: { source: "jhing", target: "vshirley" } },
    { group: "edges", data: { source: "kdecker", target: "amoore" } },
    { group: "edges", data: { source: "kdecker", target: "mlanahan" } },
    { group: "edges", data: { source: "fswarr", target: "atisaranni" } },
    { group: "edges", data: { source: "fswarr", target: "csisko" } },
    { group: "edges", data: { source: "ileon", target: "kweaver" } },
    { group: "edges", data: { source: "measton", target: "cswords" } },
    { group: "edges", data: { source: "measton", target: "ileon" } },
    { group: "edges", data: { source: "ahopkins", target: "measton" } },
    { group: "edges", data: { source: "ahopkins", target: "lblackwell" } },
    { group: "edges", data: { source: "anoori", target: "fswarr" } },
    { group: "edges", data: { source: "atisaranni", target: "kdecker" } },
    { group: "edges", data: { source: "vshirley", target: "oloris" } },
    { group: "edges", data: { source: "crush", target: "rhutchison" } },
    { group: "edges", data: { source: "crush", target: "tpaige" } },
    { group: "edges", data: { source: "skaynor", target: "asullivan" } },
    { group: "edges", data: { source: "ajunkin", target: "gspitaletto" } },
    { group: "edges", data: { source: "rwhitman", target: "ahopkins" } },
    { group: "edges", data: { source: "athornton", target: "crush" } },
    { group: "edges", data: { source: "zhardin", target: "pczaja" } }, //ADDED BY AVERY 2/17
    { group: "edges", data: { source: "zhardin", target: "jstevens" } },
    { group: "edges", data: { source: "zhardin", target: "ctomasky" } },
    { group: "edges", data: { source: "zhardin", target: "aquarra" } },
    { group: "edges", data: { source: "afrench", target: "ahaughwout" } },
    { group: "edges", data: { source: "rlamb", target: "ccapawana" } },
    { group: "edges", data: { source: "rblomquist", target: "sfivndraat" } },//ADD RBLOMQUIST YOU CLOWN
    { group: "edges", data: { source: "sfijnvandraat", target: "tross" } },
    { group: "edges", data: { source: "kmobley", target: "jnichols" } },
    // TODO: Add Garrett to Maddie, Maddie to Riley, then Garrett to Elizabeth, and Elizabeth to Sam
    
  ],
};

export default member_list;
